NULL

#' V-Dem data
#'
#' Loads the most recent version of the V-Dem data set.
#'
#' Varieties of Democracy (V-Dem) is a new approach to conceptualizing
#' and measuring democracy. We provide a multidimensional and disaggregated
#' dataset that reflects the complexity of the concept of democracy as a
#' system of rule that goes beyond the simple presence of elections.
#' The V-Dem project distinguishes between five high-level principles of
#' democracy: electoral, liberal, participatory, deliberative, and
#' egalitarian, and collects data to measure these principles.
#' With five Principal Investigators (PIs), thirty-nine Project Managers
#' (PMs) with special responsibility for issue areas,
#' more than thirty Regional Managers (RMs),
#' 134 Country Coordinators (CCs), Research Assistants,
#' and over 4,000 Country Experts (CEs). The V-Dem project is one
#' of the largest social science data collection projects
#' focusing on research. The Headquarters is based at the
#' V-Dem Institute, the Department of Political Science at the
#' University of Gothenburg, Sweden. The most recent data set (v15)
#' covers 202 countries from 1789-2024 and includes 500+ indicators,
#' 81 indices and 5 high-level indices.
#' For more info see https://www.v-dem.net/
#'
#'
#' @format A data frame with 27913 observations and 4607 variables.
#'
#' @references Coppedge, Michael, John Gerring, Carl Henrik Knutsen, Staffan I. Lindberg, Jan Teorell, David Altman, Fabio Angiolillo, Michael Bernhard, Agnes Cornell, M. Steven Fish, Linnea Fox, Lisa Gastaldi, Haakon Gjerløw, Adam Glynn, Ana Good God, Sandra Grahn, Allen Hicken, Katrin Kinzelbach, Joshua Krusell, Kyle L. Marquardt, Kelly McMann, Valeriya Mechkova, Juraj Medzihorsky, Natalia Natsika, Anja Neundorf, Pamela Paxton, Daniel Pemstein, Johannes von Römer, Brigitte Seim, Rachel Sigman, Svend-Erik Skaaning, Jeffrey Staton, Aksel Sundström, Marcus Tannenberg, Eitan Tzelgov, Yi-ting Wang, Felix Wiebrecht, Tore Wig, Steven Wilson and Daniel Ziblatt. 2025. "V-Dem Country-Year Dataset v15" Varieties of Democracy (V-Dem) Project. https://doi.org/10.23696/vdemds25.
#'
#' @source https://www.v-dem.net
#'
"vdem"

#' V-Dem codebook
#'
#' Loads as data frame selected information from the V-Dem dataset codebook
#'
#' For the full pdf version of the codebook and more info see https://www.v-dem.net
#'
#'
#' @format A data frame with 828 observations and 14 variables.
#'
#' @references Coppedge, Michael, John Gerring, Carl Henrik Knutsen, Staffan I. Lindberg, Jan Teorell, David Altman, Fabio Angiolillo, Michael Bernhard, Agnes Cornell, M. Steven Fish, Linnea Fox, Lisa Gastaldi, Haakon Gjerløw, Adam Glynn, Ana Good God, Sandra Grahn, Allen Hicken, Katrin Kinzelbach, Kyle L. Marquardt, Kelly McMann, Valeriya Mechkova, Anja Neundorf, Pamela Paxton, Daniel Pemstein, Johannes von Römer, Brigitte Seim, Rachel Sigman, Svend-Erik Skaaning, Jeffrey Staton, Aksel Sundström, Marcus Tannenberg, Eitan Tzelgov, Yi-ting Wang, Felix Wiebrecht, Tore Wig, and Daniel Ziblatt. 2025. "V-Dem Codebook v15" Varieties of Democracy (V-Dem) Project. https://v-dem.net/data/reference-documents/
#'
#' @source https://www.v-dem.net
#'
"codebook"


#' Episodes of Regime Transformation (ERT)
#' 
#' Country-year data on episodes of regime transformation. 
#' 
#' @format A country-year dataset (class "tibble::tbl_df") with corresponding
#'   to the full V-Dem data set of cases, with three dozen columns related to
#'   the ERT coding. Key columns include:
#'   
#' \describe{
#'     \item{country_id}{V-Dem numeric country identifier}
#'     \item{year}{Year}
#'     \item{dem_ep}{Binary indicator for a democratization episode}
#'     \item{aut_ep}{Binary indicator for an autocratization episode}
#' }
#' 
#' For information on the remaining columns, see the ERT codebook, which is 
#' installed along with the package. Try the following code to open it, might
#' not work on Windows: 
#' 
#' \code{browseURL(system.file("ERT_codebook.pdf", package = "ERT"))}
#' 
#' @details These data can be re-generated by running [get_eps()] with the 
#' default settings.
#' 
#' @examples
#' data(episodes)
#' dplyr::glimpse(episodes)
"episodes"

