# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identify sequences of potential autocratization episodes
#'
#' This is a subfunction (c++) of ERT::get_eps see the
#' documentation of ERT::get_aut (?get_eps) for details on
#' parameters, etc.
#'
find_seqs_aut <- function(v, r, t, start_incl = -0.01, year_turn = 0.03, cum_turn = 0.1, tolerance = 5L) {
    .Call('_ERT_find_seqs_aut', PACKAGE = 'ERT', v, r, t, start_incl, year_turn, cum_turn, tolerance)
}

#' Identify sequences of potential democratization episodes
#'
#' This is a subfunction (c++) of ERT::get_eps see the
#' documentation of ERT::get_eps (?get_eps) for details on
#' parameters, etc.
#'
find_seqs_dem <- function(v, r, t, start_incl = 0.01, year_turn = -0.03, cum_turn = -0.1, tolerance = 5L) {
    .Call('_ERT_find_seqs_dem', PACKAGE = 'ERT', v, r, t, start_incl, year_turn, cum_turn, tolerance)
}

